### ISSUE TITLE
can't clone repo

### ISSUE THREAD

**Issue by giovp** [Mu-DS/practical_training#1]
```
Error downloading object: 03_continuous_integration/knn_iris_model.model (fa01c98): Smudge error: Error downloading 03_continuous_integration/knn_iris_model.model (fa01c9852f921cd486772319ed3b76e6712064998a6639f01977a8e171dcdac3): [fa01c9852f921cd486772319ed3b76e6712064998a6639f01977a8e171dcdac3] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to /Users/giovanni.palla/Projects/practical_training/.git/lfs/logs/20200719T164748.308574.log
```

error during cloning. 

Possibly linked to this: c087317e630f5a23f4071aed4c0df02760c67c17

**Comment by aliechoes** [comment]
I tried to clone the repo in an independent place and everything worked out with no problem! Are you sure the lfs is correctly configured?

**Comment by aliechoes** [comment]
also, what is your os?

**Comment by giovp** [comment]
lfs seems correct. I have mac. Do you also have this problem @the-rccg ?

**Comment by e-dorigatti** [comment]
Works for me, on arch linux

**Comment by e-dorigatti** [comment]
@giovp  Can you post the content of `/Users/giovanni.palla/Projects/practical_training/.git/lfs/logs/20200719T164748.308574.log` ?

**Comment by giovp** [comment]
apparently, there is no log if I do `git lfs logs last` and there is no file if I look into the folder you pointed to.
this is the full error:
```
$ git clone https://github.com/Mu-DS/practical_training.git
Cloning into 'practical_training'...
remote: Enumerating objects: 128, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 128 (delta 59), reused 47 (delta 19), pack-reused 0
Receiving objects: 100% (128/128), 11.80 MiB | 5.96 MiB/s, done.
Resolving deltas: 100% (59/59), done.
Downloading 03_continuous_integration/knn_iris_model.model (6.6 KB)
Error downloading object: 03_continuous_integration/knn_iris_model.model (fa01c98): Smudge error: Error downloading 03_continuous_integration/knn_iris_model.model (fa01c9852f921cd486772319ed3b76e6712064998a6639f01977a8e171dcdac3): [fa01c9852f921cd486772319ed3b76e6712064998a6639f01977a8e171dcdac3] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to /Users/giovanni.palla/practical_training/.git/lfs/logs/20200724T103154.585153.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: 03_continuous_integration/knn_iris_model.model: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by giovp** [comment]
googling found this possible issue maybe related [link](https://github.com/git-lfs/git-lfs/issues/3519#issuecomment-605915137)

but, on a broader perspective, if I am having this issue, what are the chances that other 20 people's have it?

**Comment by giovp** [comment]
and so how much effort do we want to put in get it to work for other people?

**Comment by the-rccg** [comment]
I have been able to pull on my machine under windows. I'll have to check if I can clone it too, once I'm back on my computer.

**Comment by e-dorigatti** [comment]
Okay I managed to reproduce the error by installing `git-lfs` and doing `git lfs install` followed by `git lfs fetch`. Now it also happens when cloning. According to my googling ([here][h1], [here][h2] and [here][h3]) this can happen if there was an error when pushing. @aliechoes can you try running 

```
git lfs push --object-id origin fa01c98
```

[h1]: https://stackoverflow.com/a/54433489
[h2]: https://github.com/git-lfs/git-lfs/issues/1935#issuecomment-336265781
[h3]: https://github.com/git-lfs/git-lfs/issues/3525#issuecomment-464955665

**Comment by aliechoes** [comment]
@giovp thanks for pointing out the error. 
I *intentionally* used lfs as I wanted to show an example of it to other people. Of course we have to check things before starting the course

@e-dorigatti I will check and let you know

**Comment by aliechoes** [comment]
ok the issue should be solved now! 
The problem was coming from gitkraken windows, having some internal problems with git hooks and git lfs. I had to use a linux machine to solve the issue  
@giovp can you please double check if the issue is solved on your side or not?

**Comment by giovp** [comment]
seems like it is, I can clone and master seems fine. Thanks @aliechoes !
